import { designSystem } from "./designSystem";

export const colors = {
  background: designSystem.colors.background,
  backgroundAlt: designSystem.colors.backgroundAlt,
  backgroundDecor: designSystem.colors.backgroundDecor,
  surface: designSystem.colors.surface,
  surfaceElevated: designSystem.colors.surfaceElevated,
  surfaceSecondary: designSystem.colors.surfaceSecondary,
  surfaceMuted: designSystem.colors.surfaceMuted,
  surfacePressed: designSystem.colors.surfacePressed,
  primary: designSystem.colors.primary,
  primaryPressed: designSystem.colors.primaryPressed,
  primarySoft: designSystem.colors.primarySoft,
  primaryFaint: designSystem.colors.primaryFaint,
  onPrimary: designSystem.colors.textInverted,
  textPrimary: designSystem.colors.textPrimary,
  textSecondary: designSystem.colors.textSecondary,
  textMuted: designSystem.colors.textMuted,
  textDisabled: designSystem.colors.textDisabled,
  border: designSystem.colors.border,
  borderStrong: designSystem.colors.borderStrong,
  divider: designSystem.colors.divider,
  overlay: designSystem.colors.overlay,
  shadow: designSystem.colors.shadow,
  success: designSystem.colors.success,
  successSoft: designSystem.colors.successSoft,
  successBorder: designSystem.colors.successBorder,
  warning: designSystem.colors.warning,
  warningSoft: designSystem.colors.warningSoft,
  warningBorder: designSystem.colors.warningBorder,
  error: designSystem.colors.danger,
  errorSoft: designSystem.colors.dangerSoft,
  errorBorder: designSystem.colors.dangerBorder,
  info: designSystem.colors.info,
  infoSoft: designSystem.colors.infoSoft,
  infoBorder: designSystem.colors.infoBorder,
  skeletonBase: designSystem.colors.skeletonBase,
  skeletonHighlight: designSystem.colors.skeletonHighlight,
} as const;
