export const designSystem = {
  colors: {
    background: "#FFFCF8",
    backgroundAlt: "#F7FBF8",
    surface: "#FFFFFF",
    surfaceMuted: "#F7F4EF",
    surfacePressed: "#FFF1E2",
    primary: "#F76502",
    primaryPressed: "#DE5700",
    primarySoft: "#FFE0C6",
    primaryFaint: "#FFF5EA",
    secondary: "#246B61",
    secondarySoft: "#E8F4F1",
    accent: "#6E55B7",
    accentSoft: "#F0EDFA",
    textPrimary: "#111827",
    textSecondary: "#4B5563",
    textMuted: "#6B7280",
    textInverted: "#FFFFFF",
    border: "#F0DFC9",
    borderStrong: "#E7C9A8",
    success: "#239447",
    successSoft: "#E7F7E8",
    successBorder: "#BFE9C3",
    warning: "#D97706",
    warningSoft: "#FFF0D6",
    warningBorder: "#FFD89A",
    danger: "#D62828",
    dangerSoft: "#FDECEC",
    dangerBorder: "#F7C7C7",
    info: "#46627A",
    infoSoft: "#EDF4FA",
    infoBorder: "#C9DAE8",
    neutral: "#64748B",
    neutralSoft: "#F1F5F9",
    neutralBorder: "#D7DEE8",
    shadow: "rgba(92, 58, 32, 0.10)",
    overlay: "rgba(17, 24, 39, 0.36)",
  },
  typography: {
    families: {
      regular: undefined,
      medium: undefined,
      bold: undefined,
    },
    weights: {
      regular: "400",
      medium: "500",
      semiBold: "600",
      bold: "700",
    },
    sizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 24,
      xxl: 30,
    },
    lineHeights: {
      xs: 16,
      sm: 20,
      md: 24,
      lg: 26,
      xl: 30,
      xxl: 36,
    },
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 40,
  },
  radii: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    pill: 999,
  },
  shadows: {
    none: {
      shadowOpacity: 0,
      elevation: 0,
    },
    sm: {
      shadowColor: "rgba(92, 58, 32, 0.08)",
      shadowOpacity: 1,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    md: {
      shadowColor: "rgba(92, 58, 32, 0.10)",
      shadowOpacity: 1,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 7 },
      elevation: 2,
    },
  },
  iconSizes: {
    xs: 14,
    sm: 18,
    md: 22,
    lg: 26,
    xl: 32,
  },
  animation: {
    fast: 120,
    normal: 220,
    slow: 360,
  },
} as const;

export type DesignSystem = typeof designSystem;
