const lightColors = {
  background: "#FFF6EC",
  backgroundAlt: "#FBEBD9",
  backgroundDecor: "#FFE7CE",
  surface: "#FFFDF9",
  surfaceElevated: "#FFFFFF",
  surfaceSecondary: "#F8EFE4",
  surfaceMuted: "#F3E7DA",
  surfacePressed: "#FFF0DE",
  primary: "#F26A21",
  primaryPressed: "#D95A16",
  primarySoft: "#FFD7B8",
  primaryFaint: "#FFF1E3",
  secondary: "#1F6F63",
  secondarySoft: "#E3F3EE",
  accent: "#5D6FA3",
  accentSoft: "#EBEFFA",
  success: "#228A44",
  successSoft: "#E7F7EA",
  successBorder: "#B9E4C2",
  warning: "#B97008",
  warningSoft: "#FFF0D0",
  warningBorder: "#F4CF89",
  danger: "#C9342E",
  dangerSoft: "#FCEAE8",
  dangerBorder: "#F0BDB8",
  info: "#3E6078",
  infoSoft: "#E8F1F7",
  infoBorder: "#C5D8E5",
  neutral: "#687385",
  neutralSoft: "#EEF2F5",
  neutralBorder: "#D4DCE4",
  textPrimary: "#241912",
  textSecondary: "#645247",
  textMuted: "#8A7668",
  textDisabled: "#B7A89B",
  textInverted: "#FFFDF8",
  border: "#ECD9C5",
  borderStrong: "#DDBB98",
  divider: "rgba(94, 71, 52, 0.12)",
  overlay: "rgba(31, 21, 13, 0.42)",
  skeletonBase: "#EBDCCD",
  skeletonHighlight: "#FFF4E6",
  shadow: "rgba(80, 47, 24, 0.13)",
  qrBackground: "#FFFFFF",
} as const;

const darkColors = {
  background: "#1A140F",
  backgroundAlt: "#241A13",
  backgroundDecor: "#332316",
  surface: "#241D18",
  surfaceElevated: "#302620",
  surfaceSecondary: "#2B211A",
  surfaceMuted: "#3A2C23",
  surfacePressed: "#3D2A1D",
  primary: "#FF8A3D",
  primaryPressed: "#F47522",
  primarySoft: "#5B351F",
  primaryFaint: "#352317",
  secondary: "#72CBB9",
  secondarySoft: "#173A34",
  accent: "#AAB8F1",
  accentSoft: "#252C49",
  success: "#7EDB94",
  successSoft: "#173A22",
  successBorder: "#2B7241",
  warning: "#F4BE54",
  warningSoft: "#3E2A10",
  warningBorder: "#7A5518",
  danger: "#FF8C84",
  dangerSoft: "#421C1B",
  dangerBorder: "#803A36",
  info: "#9AC4DF",
  infoSoft: "#172C3A",
  infoBorder: "#355D72",
  neutral: "#BBC4D0",
  neutralSoft: "#2A3037",
  neutralBorder: "#46515C",
  textPrimary: "#FFF6EC",
  textSecondary: "#D8C8B8",
  textMuted: "#AE9A89",
  textDisabled: "#74655A",
  textInverted: "#1D130C",
  border: "rgba(255, 238, 218, 0.14)",
  borderStrong: "rgba(255, 238, 218, 0.24)",
  divider: "rgba(255, 238, 218, 0.10)",
  overlay: "rgba(3, 2, 1, 0.62)",
  skeletonBase: "#382A21",
  skeletonHighlight: "#4A382D",
  shadow: "rgba(0, 0, 0, 0.42)",
  qrBackground: "#FFFFFF",
} as const;

export const designSystem = {
  themes: {
    light: lightColors,
    dark: darkColors,
  },
  colors: lightColors,
  typography: {
    families: {
      regular: undefined,
      medium: undefined,
      bold: undefined,
    },
    weights: {
      regular: "400",
      medium: "500",
      semiBold: "600",
      bold: "700",
      extraBold: "800",
    },
    sizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 22,
      xxl: 28,
      display: 34,
    },
    lineHeights: {
      xs: 16,
      sm: 20,
      md: 24,
      lg: 26,
      xl: 28,
      xxl: 34,
      display: 40,
    },
    letterSpacing: {
      tight: 0,
      normal: 0,
      wide: 0.2,
    },
    roles: {
      display: {
        fontSize: 34,
        lineHeight: 40,
        fontWeight: "800",
        letterSpacing: 0,
      },
      heroTitle: {
        fontSize: 28,
        lineHeight: 34,
        fontWeight: "800",
        letterSpacing: 0,
      },
      screenTitle: {
        fontSize: 22,
        lineHeight: 28,
        fontWeight: "700",
        letterSpacing: 0,
      },
      sectionTitle: {
        fontSize: 18,
        lineHeight: 24,
        fontWeight: "700",
        letterSpacing: 0,
      },
      cardTitle: {
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "700",
        letterSpacing: 0,
      },
      body: {
        fontSize: 16,
        lineHeight: 24,
        fontWeight: "400",
        letterSpacing: 0,
      },
      bodySmall: {
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "400",
        letterSpacing: 0,
      },
      label: {
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "600",
        letterSpacing: 0.2,
      },
      caption: {
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "500",
        letterSpacing: 0.2,
      },
      button: {
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
        letterSpacing: 0.2,
      },
      price: {
        fontSize: 18,
        lineHeight: 24,
        fontWeight: "800",
        letterSpacing: 0,
      },
    },
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 40,
    giant: 48,
    screenHorizontal: 16,
    sectionGap: 24,
    cardPadding: 16,
    buttonPaddingHorizontal: 18,
    inputHeight: 50,
    chipHeight: 36,
    listGap: 12,
    tabSafePadding: 88,
  },
  radii: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 30,
    chip: 999,
    input: 16,
    button: 16,
    cardSm: 16,
    cardLg: 24,
    modal: 28,
    image: 18,
    floating: 999,
    pill: 999,
  },
  shadows: {
    none: {
      shadowOpacity: 0,
      elevation: 0,
    },
    low: {
      shadowColor: lightColors.shadow,
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    medium: {
      shadowColor: lightColors.shadow,
      shadowOpacity: 1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    high: {
      shadowColor: lightColors.shadow,
      shadowOpacity: 1,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 14 },
      elevation: 6,
    },
    modal: {
      shadowColor: "rgba(24, 15, 8, 0.24)",
      shadowOpacity: 1,
      shadowRadius: 34,
      shadowOffset: { width: 0, height: 18 },
      elevation: 9,
    },
    sm: {
      shadowColor: lightColors.shadow,
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    md: {
      shadowColor: lightColors.shadow,
      shadowOpacity: 1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  },
  iconSizes: {
    xs: 14,
    sm: 18,
    md: 22,
    lg: 28,
    xl: 36,
  },
  motion: {
    instant: 80,
    fast: 140,
    normal: 220,
    slow: 360,
    enter: 260,
    exit: 180,
    stagger: 42,
    press: 90,
    spring: {
      damping: 18,
      stiffness: 190,
      mass: 0.8,
    },
  },
  animation: {
    fast: 140,
    normal: 220,
    slow: 360,
  },
  components: {
    button: {
      heightSm: 38,
      heightMd: 50,
      heightLg: 56,
    },
    input: {
      minHeight: 50,
    },
    tabBar: {
      height: 58,
    },
  },
} as const;

export type DesignSystem = typeof designSystem;
