import { designSystem } from "./designSystem";

export const studentPalette = {
  background: designSystem.colors.background,
  backgroundStrong: "#FFF4E8",
  backgroundSoft: designSystem.colors.background,
  primary: designSystem.colors.primary,
  primaryPressed: designSystem.colors.primaryPressed,
  primarySoft: designSystem.colors.primarySoft,
  primaryPale: "#FFF1E2",
  primaryFaint: designSystem.colors.primaryFaint,
  decorOrange: "rgba(247, 101, 2, 0.18)",
  decorOrangeSoft: "rgba(247, 101, 2, 0.10)",
  card: designSystem.colors.surface,
  cardMuted: designSystem.colors.surface,
  textPrimary: designSystem.colors.textPrimary,
  textSecondary: designSystem.colors.textSecondary,
  textMuted: designSystem.colors.textMuted,
  border: designSystem.colors.border,
  borderStrong: designSystem.colors.borderStrong,
  shadow: "rgba(92, 58, 32, 0.08)",
  success: designSystem.colors.success,
  successSoft: designSystem.colors.successSoft,
  successBorder: designSystem.colors.successBorder,
  danger: designSystem.colors.danger,
  dangerSoft: designSystem.colors.dangerSoft,
  dangerBorder: designSystem.colors.dangerBorder,
  warning: designSystem.colors.warning,
  warningSoft: designSystem.colors.warningSoft,
  warningBorder: designSystem.colors.warningBorder,
  info: designSystem.colors.info,
  infoSoft: designSystem.colors.infoSoft,
  infoBorder: designSystem.colors.infoBorder,
  neutral: designSystem.colors.neutral,
  neutralSoft: designSystem.colors.neutralSoft,
  neutralBorder: designSystem.colors.neutralBorder,
} as const;
