import { designSystem } from "./designSystem";

export const studentPalette = {
  background: designSystem.colors.background,
  backgroundStrong: designSystem.colors.backgroundDecor,
  backgroundSoft: designSystem.colors.background,
  primary: designSystem.colors.primary,
  primaryPressed: designSystem.colors.primaryPressed,
  primarySoft: designSystem.colors.primarySoft,
  primaryPale: designSystem.colors.primarySoft,
  primaryFaint: designSystem.colors.primaryFaint,
  decorOrange: "rgba(242, 106, 33, 0.18)",
  decorOrangeSoft: "rgba(242, 106, 33, 0.10)",
  card: designSystem.colors.surface,
  cardMuted: designSystem.colors.surfaceSecondary,
  cardElevated: designSystem.colors.surfaceElevated,
  textPrimary: designSystem.colors.textPrimary,
  textSecondary: designSystem.colors.textSecondary,
  textMuted: designSystem.colors.textMuted,
  textDisabled: designSystem.colors.textDisabled,
  border: designSystem.colors.border,
  borderStrong: designSystem.colors.borderStrong,
  divider: designSystem.colors.divider,
  shadow: designSystem.colors.shadow,
  success: designSystem.colors.success,
  successSoft: designSystem.colors.successSoft,
  successBorder: designSystem.colors.successBorder,
  danger: designSystem.colors.danger,
  dangerSoft: designSystem.colors.dangerSoft,
  dangerBorder: designSystem.colors.dangerBorder,
  warning: designSystem.colors.warning,
  warningSoft: designSystem.colors.warningSoft,
  warningBorder: designSystem.colors.warningBorder,
  info: designSystem.colors.info,
  infoSoft: designSystem.colors.infoSoft,
  infoBorder: designSystem.colors.infoBorder,
  neutral: designSystem.colors.neutral,
  neutralSoft: designSystem.colors.neutralSoft,
  neutralBorder: designSystem.colors.neutralBorder,
} as const;
