export const ROUTES = {
  Welcome: "Welcome",
  StudentAccess: "StudentAccess",
  Login: "Login",
  CreateRestaurant: "CreateRestaurant",
  ManagerProfile: "ManagerProfile",
  AddDish: "AddDish",
  SuperAdmin: "SuperAdmin",
  Home: "Home",
  RestaurantDetail: "RestaurantDetail",
  FoodDetail: "FoodDetail",
  Cart: "Cart",
  Checkout: "Checkout",
  ReservationTracking: "ReservationTracking",
  ManagerQrScanner: "ManagerQrScanner",
  Notifications: "Notifications",
  Appearance: "Appearance",
  Rating: "Rating",
  ProblemReport: "ProblemReport",
  Help: "Help",
  LocalPending: "LocalPending",
  OnboardingReview: "OnboardingReview",
  OnboardingStageDetail: "OnboardingStageDetail",
  OnboardingFull: "OnboardingFull",
  HelpDetail: "HelpDetail",
  PendingDetail: "PendingDetail",
  MyReservations: "MyReservations",
  Profile: "Profile",
  Register: "Register",

  SuperAdminTabs: "SuperAdminTabs",
  SuperAdminRestaurants: "SuperAdminRestaurants",
  SuperAdminUsers: "SuperAdminUsers",
  SuperAdminUserDetail: "SuperAdminUserDetail",
  SuperAdminAssignManager: "SuperAdminAssignManager",
  SuperAdminUserRole: "SuperAdminUserRole",
  SuperAdminUserStatus: "SuperAdminUserStatus",
} as const;
